COCO_INSTANCE_CATEGORY_NAMES = [
    '__background__', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck',
    'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog',
    'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag',
    'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat',
    'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup',
    'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot',
    'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table',
    'toilet', 'TV', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven',
    'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier',
    'toothbrush', 'smartphone', 'drone', 'guitar', 'skateboard', 'printer', 'laptop bag', 'backhoe', 'excavator',
    'shovel', 'hammer', 'wrench', 'saw', 'pliers', 'drill', 'torch', 'screwdriver', 'scissors', 'tape',
    'paintbrush', 'ladder', 'wheelbarrow', 'rake', 'lawn mower', 'trolley', 'vacuum cleaner', 'fan',
    'air conditioner', 'space heater', 'lamp', 'chandelier', 'shelf', 'recliner', 'armchair', 'ottoman',
    'pillow', 'blanket', 'quilt', 'mirror', 'nightstand', 'dresser', 'wardrobe', 'closet', 'shower',
    'bathtub', 'laundry basket', 'toothpaste', 'soap', 'shampoo', 'conditioner', 'comb', 'towel',
    'toilet paper', 'first aid kit', 'medicine bottle', 'bandage', 'thermometer', 'scalp massager',
    'glasses', 'contacts', 'sunglasses', 'hat', 'cap', 'scarf', 'gloves', 'boots', 'sandals', 'flip flops',
    'shoes', 'umbrella', 'raincoat', 'jacket', 'coat', 'sweater', 'jeans', 'pants', 'shorts', 'skirt',
    'dress', 't-shirt', 'shirt', 'socks', 'tie', 'belt', 'watch', 'bracelet', 'necklace', 'ring',
    'earrings', 'wallet', 'purse', 'backpack', 'luggage', 'bag', 'phone case', 'headphones', 'earphones',
    'Bluetooth speaker', 'microphone', 'speaker', 'projector', 'camera', 'tripod', 'lens', 'filter',
    'memory card', 'charging cable', 'power bank', 'flashlight', 'battery', 'battery charger',
    'wireless charger', 'keyboard', 'mouse', 'touchpad', 'monitor', 'tablet', 'e-reader', 'printer',
    'scanner', 'fax machine', 'copy machine', 'shredder', 'webcam', 'microSD card', 'hard drive',
    'SSD', 'desktop', 'laptop', 'workstation', 'server', 'router', 'modem', 'Wi-Fi router', 'Ethernet cable',
    'USB drive', 'external hard drive', 'dock station', 'charging pad', 'computer case', 'desktop monitor',
    'television', 'radio', 'microwave', 'oven', 'blender', 'juicer', 'coffee maker', 'kettle', 'toaster',
    'frying pan', 'pot', 'pan', 'knife block', 'cutting board', 'mixer', 'grater', 'peeler', 'can opener',
    'measuring cup', 'spatula', 'whisk', 'sifter', 'tongs', 'strainer', 'colander', 'cooking pot', 'steamer',
    'dishwasher', 'washing machine', 'dryer', 'fridge', 'freezer', 'kitchen sink', 'sink faucet',
    'coffee grinder', 'toothbrush holder', 'soap dispenser', 'hairbrush', 'toothpaste tube', 'toilet brush',
    'hair clip', 'comb', 'toilet mat', 'shower curtain', 'bath mat', 'shower shelf', 'drain cover',
    'toilet plunger', 'laundry detergent', 'fabric softener', 'dryer sheets', 'laundry hamper', 'dryer rack',
    'laundry machine', 'vacuum bag', 'laundry line', 'dustpan', 'broom', 'mop', 'bucket', 'dish towel',
    'clothes iron', 'iron board', 'clothes hanger', 'laundry basket', 'garbage bag', 'garbage can',
    'recycling bin', 'compost bin', 'cleaning products', 'hand sanitizer', 'disinfectant', 'cleaning cloth',
    'hand wipes', 'disposable gloves', 'sanitizer spray', 'dish soap', 'toilet cleaner', 'floor cleaner',
    'stove cleaner', 'oven cleaner', 'window cleaner', 'multi-surface cleaner', 'broom', 'dust cloth',
    'laundry line', 'scouring pad', 'dust mop', 'vacuum', 'air freshener', 'odor eliminator', 'room spray',
    'furniture polish', 'garbage disposal', 'vacuum filter', 'steam cleaner', 'dehumidifier', 'humidifier',
    'air purifier', 'space heater', 'air purifier filter', 'humidifier filter', 'dehumidifier filter',
    'door mat', 'welcome mat', 'rain boot', 'mudroom rug', 'shoe rack', 'storage chest', 'storage box',
    'drawer organizer', 'shelf organizer', 'coatrack', 'umbrella stand', 'key holder', 'doorknob', 'lock',
    'door handle', 'doorbell', 'welcome sign', 'front door', 'back door', 'window blinds', 'curtains',
    'wall clock', 'wall mirror', 'decorative vase', 'photo frame', 'artwork', 'painting', 'picture frame',
    'wall decal', 'poster', 'lamp shade', 'table lamp', 'floor lamp', 'candle holder', 'incense holder',
    'vase with flowers', 'potted plant', 'plant pot', 'flower pot', 'fountain', 'rocking chair', 'lounger',
    'patio chair', 'umbrella stand', 'outdoor bench', 'garden gnome', 'garden tool', 'barbecue grill',
    'outdoor table', 'garden furniture', 'fountain', 'birdbath', 'birdhouse', 'garden hose', 'lawn chair',
    'shovel', 'rake', 'lawn mower', 'hedge trimmer', 'spade', 'weed trimmer', 'gardening gloves',
    'wheelbarrow', 'garden trowel', 'picket fence', 'stone path', 'garden rake', 'watering can', 'sprinkler',
    'garden spade', 'sod', 'compost bin', 'garden cart', 'plant trellis', 'garden bench', 'garden shovel',
    'paving stone', 'seeds', 'flower bed', 'tree stump', 'bird feeder', 'insect hotel', 'hedge trimmer',
    'power washer', 'outdoor speaker', 'outdoor heater', 'solar lights', 'outdoor rug', 'garden umbrella',
    'garden gate', 'trellis', 'deck', 'patio', 'awning', 'canopy', 'fire pit', 'outdoor fireplace',
    'lantern', 'grill', 'chiminea', 'backyard', 'patio furniture', 'outdoor light', 'picnic table',
    'hammock', 'swingset', 'sandbox', 'trampoline', 'pool float', 'kiddie pool', 'pool ladder', 'diving board',
    'swimming pool', 'jacuzzi', 'hot tub', 'outdoor pool', 'beach ball', 'swim goggles', 'pool cue', 'fishing rod',
    'bait', 'boat paddle', 'fishing tackle', 'beach towel', 'life vest', 'snorkel mask', 'surfboard', 'paddleboard'
]
